name: Generate changes

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Generate changes
        run: node genFiles.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Changes Generator Bot
          commit_user_email: monitor@bundlemon.dev
          commit_author: Monitor <monitor@bundlemon.dev>
